// src/views/Tools.vue
<script lang="ts">
import { defineComponent } from 'vue'
import Pannel from '../components/Pannel.vue'
import Card from '../components/Card.vue'
import { useRouter } from 'vue-router'

interface CardItem {
  title: string
  desc: string
  path: string
}

export default defineComponent({
  components: { Pannel, Card },
  setup() {
    const router = useRouter()

    const tools: Array<CardItem> = [
      {
        title: '调色板',
        desc: '中性色板',
        path: '/colorPicker',
      },
      {
        title: '代码格式化',
        desc: 'CSS、JavaScript 代码格式化',
        path: '/formater',
      },
      {
        title: 'base64 ⇌ 图片',
        desc: '在图片与 base64 之间转换',
        path: '/convertBase64Image',
      },
    ]

    const tools2: Array<CardItem> = []

    function handleCardClick(path: string) {
      router.push({ path })
    }
    return { tools, tools2, handleCardClick }
  },
})
</script>

<template>
  <div class="mt-24 mx-auto w-2/3 <sm:(w-11/12 mt-2)">
    <Pannel title="前端工具">
      <div class="flex flex-wrap mt-2">
        <Card
          v-for="item in tools"
          :key="item.title"
          :data="item"
          @click="handleCardClick(item.path)"
        ></Card>
      </div>
    </Pannel>
  </div>
</template>

// src/pages/tools/index.tsx
import React, { Component } from 'react';
import { Row, Col, Card } from 'antd';
import { Link } from 'umi';
import {
  PictureOutlined,
  BgColorsOutlined,
  CodeOutlined,
} from '@ant-design/icons';

interface CardItem {
  title: string;
  desc: string;
  path: string;
  icon: any;
}

const toolList: Array<CardItem> = [
  {
    title: '调色板',
    desc: '中性色板',
    path: '/tools/colorPicker',
    icon: BgColorsOutlined,
  },
  {
    title: '代码格式化',
    desc: 'CSS、JavaScript 代码格式化',
    path: '/tools/formater',
    icon: CodeOutlined,
  },
  {
    title: '图片转 Base64',
    desc: '将图片转换为 Base64 编码',
    path: '/tools/imgToBase64',
    icon: PictureOutlined,
  },
];

type CardTitleProps = {
  title: string;
  children: React.ReactNode;
};

const CardTitle: React.FC<CardTitleProps> = (props) => (
  <div className="flex items-center">
    {props.children}
    <span className="ml-2">{props.title}</span>
  </div>
);

const ToolCard: React.FC<{ toolData: CardItem }> = ({ toolData }) => (
  <Link to={toolData.path}>
    <Card
      title={<CardTitle title={toolData.title} children={<toolData.icon />} />}
      bordered={true}
    >
      {toolData.desc}
    </Card>
  </Link>
);

const Index: React.FC = () => {
  return (
    <>
      <Row gutter={[16, 16]}>
        {toolList.map((item) => (
          <Col xs={24} sm={12} md={8} lg={6} key={item.title}>
            <ToolCard toolData={item}></ToolCard>
          </Col>
        ))}
      </Row>
    </>
  );
};

export default Index;
