// src/layouts/index/header.tsx
import { useState } from 'react';
import { Link } from 'umi';

interface navItem {
  title: string;
  path: string;
}

const navList: navItem[] = [
  {
    title: '首页',
    path: '/',
  },
  {
    title: '博客',
    path: '/posts',
  },
  {
    title: '项目',
    path: '/projects',
  },
  {
    title: '在线工具',
    path: '/tools',
  },
  {
    title: '软件',
    path: '/software',
  },
];

function Logo() {
  return (
    <Link to="/">
      <div className="flex items-center py-4 pl-8 pr-4 text-2xl text-gray-700">
        FE Laboratory
      </div>
    </Link>
  );
}

function Menu() {
  return (
    <nav className="flex flex-col items-center px-8 py-4 ml-auto bg-white">
      <ul className="flex items-center gap-2 <sm:flex-col">
        {navList.map((item, index) => (
          <Link to={item.path} key={index}>
            <li className="flex items-center px-3 py-2 text-gray-500 cursor-pointer hover:(text-gray-900)">
              <span v-if="typeof item.title == 'string'">{item.title}</span>
            </li>
          </Link>
        ))}
      </ul>
    </nav>
  );
}

function MobileMenu(props: any) {
  return (
    <nav className="absolute top-12 flex flex-col items-center px-8 py-4 ml-auto bg-white">
      <ul className="flex items-center gap-2 <sm:flex-col">
        {navList.map((item, index) => (
          <Link to={item.path} key={index}>
            <li className="flex items-center px-3 py-2 text-gray-500 cursor-pointer hover:(text-gray-900)">
              <span v-if="typeof item.title == 'string'">{item.title}</span>
            </li>
          </Link>
        ))}
      </ul>
    </nav>
  );
}

function MenuButton() {
  return (
    <div className="flex items-center p-8 sm:hidden">
      <div className="side-btn">
        <div className="side-btn-burger"></div>
      </div>
    </div>
  );
}

function Header() {
  const [showMobileNav, setShowMobileNav] = useState(false);

  function handleToggleMobileNav() {
    setShowMobileNav(!showMobileNav);
  }

  return (
    <header className="sticky top-0 flex flex-row items-stretch  bg-white z-30 opacity-90">
      <MenuButton />
      <Logo />
      <Menu />
      {showMobileNav && <MobileMenu />}
    </header>
  );
}

export default Header;

// src/components/Header.vue
<script lang="ts" setup>
import { ref } from 'vue'
import { HomeIcon } from '@heroicons/vue/solid'

interface NavList {
  title: string
  path: string
  iconColor: string
}

const navlist = ref<NavList[]>([
  {
    title: '首页',
    path: '/',
    iconColor: 'text-green-500',
  },
  {
    title: '工具',
    path: '/tools',

    iconColor: 'text-blue-500',
  },
  {
    title: '关于',
    path: '/about',

    iconColor: 'text-blue-500',
  },
])
</script>

<template>
  <div
    class="
      flex flex-row
      items-stretch
      sticky
      top-0
      h-14
      z-30
      bg-white
      border-gray-200 border-b-1
      shadow
      bg-opacity-90
    "
  >
    <ul class="flex items-center gap-2 pl-7">
      <router-link :to="item.path" v-for="item in navlist" :key="item.title">
        <li
          class="
            flex
            items-center
            px-2
            py-1
            cursor-pointer
            hover:(bg-gray-100
            rounded)
            select-none
          "
        >
          <span class="leading-1">{{ item.title }}</span>
        </li>
      </router-link>
    </ul>
  </div>
</template>
